
export function getMaterialsText(id){
    const materials = [
        "Hi".repeat(1025),
        "# I am a pretty butterfly. Look at me, flying in th wind. \n## AHHH. \n# Help \n# Help \n# Help \n# Help \n# Help \n# Help \n# Help ",
        "# Search Engines vs Web Browsers\n\nIn this tutorial we will explain the difference between a search engine and a web browser.\n\n## Learning Criteria\n\nBy the end of this section, you will have learned the following:\n\n- What is a web browser?\n- What is a website?\n- What is a search engine?\n- Why Confusion may come between the terms\n\n## What Is A Web Browser?\n\nA web browser is a program that can access the internet and let you visit webpages. Webpages is the name for files on the internet, and are often\ncalled simply \"pages\".\n\nExamples of web browsers are Google Chrome, Safari, Microsoft Edge and it\'s older version Internet Explorer.\n\n## What is a Website?\n\nA website is the name for a group of webpages that are linked together. Even websites such as Facebook and Youtube are simply many webpages\nthat are linked to each other. The key feature of a webpage is that you can go to different pages in the website from within a page in the website.\n\n## What Is A Search Engine?\n\nA search engine is a website that searches the Internet for webpages. Examples of search engines are Google and Bing. \n\nYou can type text into a search bar on search engines to find webpages that are related to what you typed, and these pages are usually part of their \nown website.\n\n## Where Does All The Confusion Come From?\n\nIt is easy to get the terms \"web browser\" and \"search engine\" mixed up. Often web browsers already have a default search engine built in,\nsuch that when you use the bar on the top of a web browser, it also is the input for the search engine. \n\nAlso, companies that run search engines may also have their own web browsers. For example, Google has both it\'s search engine, but also has it\'s\nown web browser Google Chrome, that starts with the Google search engine. Microsoft has the Microsoft Edge web browser, that also has the Bing search\nengine made by Microsoft. \n\nThe best way to remember the difference is that web browsers show you webpages, search engines are a group of webpages that finds other webpages.\n\n## Further Resources\:https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Pages_sites_servers_and_search_engines#:~:text=Let\'s%20make%20it%20clear%3A%20A,displays%20a%20search%20engine\'s%20homepage. ",
        "# Basic Internet Safety\n\n## Learning Criteria\n\nIn this tutorial we will cover the following:\n- how to avoid scams\n- recognizing secure websites\n\n## How to Avoid Being Scammed\n\nThe Internet is a very useful tool, but like any tool, there are some dangers. One of these dangers is the threat of scammers attempting to\ntake your money or acquire your personal information. These scams may come from email, or from social media, but there are common elements\nthat can help you avoid being scammed.\n\n1. Do not click on any links. If it\'s a scam, then the link will most likely take you to a page that may lead to complications like theft of\npersonal information, or the loss of money, or malicious files being downloaded. If the email seems slightly suspicious, don\'t click unless\nyou are 100% sure that it is legitimate. \n\n2. Verify from the source. Some scams have the scammers pretend to be government employees demanding money, or saying that your bank has made\na bad transfer and that they need osme personal information. Some scans involve pretending to be your family members. As a general rule of thumb,\nthe government and companies will, never, ever message you to ask for your personal information; if a supposed government or bank emial asks for it,\nit is almost guaranteed to be fake. If there is confusion, directly call or contact the organization (but not to the same number the message came from)\nto clarify. \n\n3. If it sounds too good to be true, it most likely is. There are scams that say that you\'ve won a prize for a contest you haven\'t entered,\nor that you\'ve earned back money from a transfer and need to click on a link to receive it. On social media, people may intend to deceive you\ninto a false connection. Trust your gut feeling; it will work as well as if someone tried to scam you in real life.\n\n\n## What Makes a Secure Website?\n\nSecure websites are websites where the connection is secured against outside influence from other computers. You can tell that they are secured\nby their hyperlink: if you check in the web browser\'s top bar on a website, you\'ll see some text; that is the hyperlink. If you click on it, it should\nshow the full link. If the link begins with \"https\", it\'s secure. In general, avoid websites whose links do not begin with \"https\".\n\n\n## Further Resources", 
        ""];

    //const materials = ["H1", "H2", "h3", "h4"]
    let m = materials[id-1];
    return m;
}
